/// Why the agent loop stopped.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StopCondition {
    /// Model returned EndTurn or MaxTokens.
    EndTurn,
    /// Reached the configured max_rounds limit.
    MaxRounds,
    /// Total tokens exceeded the budget.
    TokenBudget,
    /// Session wall-clock duration exceeded the budget.
    DurationBudget,
    /// User interrupted with Ctrl+C.
    Interrupted,
    /// Provider returned an error.
    ProviderError,
    /// Tool loop guard forced tool withdrawal / synthesis.
    ForcedSynthesis,
}

/// Result of an agent loop execution.
#[allow(dead_code)]
pub struct AgentLoopResult {
    /// All text generated by the model across all rounds.
    pub full_text: String,
    /// Number of tool use rounds executed.
    pub rounds: usize,
    /// Why the loop stopped.
    pub stop_condition: StopCondition,
    /// Total input tokens consumed during this agent call.
    pub input_tokens: u64,
    /// Total output tokens consumed during this agent call.
    pub output_tokens: u64,
    /// Total estimated cost (USD) for this agent call.
    pub cost_usd: f64,
    /// Total wall-clock latency (ms) for this agent call.
    pub latency_ms: u64,
    /// SHA-256 fingerprint of the final message sequence (for replay verification).
    pub execution_fingerprint: String,
    /// Execution timeline as JSON (from ExecutionTracker, if a plan was generated).
    pub timeline_json: Option<String>,
    /// Returned control channel receiver (Phase 43). Returned so TUI can reuse across messages.
    pub ctrl_rx: Option<tokio::sync::mpsc::UnboundedReceiver<crate::tui::events::ControlEvent>>,
}
