//! Memory entry types for persistent semantic memory.
//!
//! Each `MemoryEntry` stores a discrete piece of knowledge:
//! facts, session summaries, decisions, code snippets, or project metadata.
//! Entries are deduplicated by content hash and searchable via BM25 (FTS5).

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// The type of a memory entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryEntryType {
    /// An important fact or piece of knowledge.
    Fact,
    /// A compressed summary of a session.
    SessionSummary,
    /// A technical decision and its rationale.
    Decision,
    /// A relevant code fragment.
    CodeSnippet,
    /// Project-level metadata (structure, patterns, conventions).
    ProjectMeta,
    /// A self-reflection generated by the Reflexion loop.
    Reflection,
}

impl MemoryEntryType {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Fact => "fact",
            Self::SessionSummary => "session_summary",
            Self::Decision => "decision",
            Self::CodeSnippet => "code_snippet",
            Self::ProjectMeta => "project_meta",
            Self::Reflection => "reflection",
        }
    }

    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "fact" => Some(Self::Fact),
            "session_summary" => Some(Self::SessionSummary),
            "decision" => Some(Self::Decision),
            "code_snippet" => Some(Self::CodeSnippet),
            "project_meta" => Some(Self::ProjectMeta),
            "reflection" => Some(Self::Reflection),
            _ => None,
        }
    }
}

/// A single memory entry.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryEntry {
    pub entry_id: Uuid,
    /// Source session (None for manual/imported entries).
    pub session_id: Option<Uuid>,
    pub entry_type: MemoryEntryType,
    /// The text content of this memory.
    pub content: String,
    /// SHA-256 hash of `content` for deduplication.
    pub content_hash: String,
    /// Flexible metadata (tool name, file path, tags, etc.).
    pub metadata: serde_json::Value,
    pub created_at: DateTime<Utc>,
    /// Optional expiry time.
    pub expires_at: Option<DateTime<Utc>>,
    /// Manual relevance boost (default 1.0).
    pub relevance_score: f64,
}

/// A memory episode — groups related entries into a task-scoped unit.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryEpisode {
    pub episode_id: String,
    pub session_id: Option<String>,
    pub title: String,
    pub summary: Option<String>,
    pub started_at: DateTime<Utc>,
    pub ended_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary statistics for the memory store.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryStats {
    pub total_entries: u32,
    pub by_type: Vec<(String, u32)>,
    pub oldest_entry: Option<DateTime<Utc>>,
    pub newest_entry: Option<DateTime<Utc>>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entry_type_roundtrip() {
        let types = [
            MemoryEntryType::Fact,
            MemoryEntryType::SessionSummary,
            MemoryEntryType::Decision,
            MemoryEntryType::CodeSnippet,
            MemoryEntryType::ProjectMeta,
        ];
        for t in &types {
            let s = t.as_str();
            let parsed = MemoryEntryType::parse(s).expect("should parse");
            assert_eq!(*t, parsed);
        }
    }

    #[test]
    fn entry_type_serde_roundtrip() {
        let t = MemoryEntryType::SessionSummary;
        let json = serde_json::to_string(&t).unwrap();
        assert_eq!(json, "\"session_summary\"");
        let parsed: MemoryEntryType = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, t);
    }

    #[test]
    fn unknown_entry_type_returns_none() {
        assert!(MemoryEntryType::parse("unknown").is_none());
        assert!(MemoryEntryType::parse("").is_none());
    }

    #[test]
    fn memory_entry_serde() {
        let entry = MemoryEntry {
            entry_id: Uuid::nil(),
            session_id: None,
            entry_type: MemoryEntryType::Fact,
            content: "Rust workspace with 9 crates".to_string(),
            content_hash: "abc123".to_string(),
            metadata: serde_json::json!({}),
            created_at: Utc::now(),
            expires_at: None,
            relevance_score: 1.0,
        };
        let json = serde_json::to_string(&entry).unwrap();
        let parsed: MemoryEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.entry_type, MemoryEntryType::Fact);
        assert_eq!(parsed.content, "Rust workspace with 9 crates");
    }

    #[test]
    fn memory_stats_serde() {
        let stats = MemoryStats {
            total_entries: 42,
            by_type: vec![("fact".into(), 30), ("decision".into(), 12)],
            oldest_entry: None,
            newest_entry: Some(Utc::now()),
        };
        let json = serde_json::to_string(&stats).unwrap();
        let parsed: MemoryStats = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.total_entries, 42);
    }
}
